// export { default as ITHLogo } from "./png/ITHLogo.png";
export { default as ITHLogo } from "./png/ITHLogo.png";
export { default as HeroImage } from "./png/hero-image.png";
export { default as DellLogo } from "./png/dell-logo.png";
export { default as ZohoLogo } from "./png/zoho-logo.png";
export { default as SophosLogo } from "./png/sophos-logo.png";
export { default as IBMLogo } from "./png/ibm-logo.png";
export { default as CiscoLogo } from "./png/cisco-logo.png";
export { default as MicrosoftLogo } from "./png/microsoft-logo.png";
export { default as DellEMCLogo } from "./png/dell-emc-logo.png";
export { default as HpLogo } from "./png/hp-logo.png";
export { default as TermiiLogo } from "./png/termii-logo.png";
// export { default as LenovoLogo } from "./png/lenovo-logo.png";
export { default as CommScopeLogo } from "./png/commscope.png";
export { default as ExpressWalletLogo } from "./png/express-wallet-logo.png";
export { default as Infrastructure } from "./png/infrastructure-image.png";
export { default as SoftwareDevImage } from "./png/software-dev-image.png";
export { default as Fintech } from "./png/fintech.png";
export { default as WhoAreWeImg } from "./png/who-are-we-image.png";
export { default as LightImage } from "./png/light-image.png";
export { default as PartnersImage } from "./png/partners-image.png";
export { default as SecurityTrainingImg } from "./png/security-training-img.png";
export { default as BusinessEmailImg } from "./png/business-email-img.png";
export { default as ContactHeroImg } from "./png/contact-hero-image.png";
export { default as MediaHeroImg } from "./png/media-hero-image.png";
export { default as HostImage } from "./png/host-images.png";
export { default as InfrastructureImage } from "./png/infrastructure-img.png";
export { default as TechnologyImg } from "./png/technology-img.png";
export { default as GalleryImageOne } from "./png/gallery-image-one.png";
export { default as GalleryImageTwo } from "./png/gallery-image-two.png";
export { default as GalleryImageThree } from "./png/gallery-image-three.png";
export { default as GalleryImageFour } from "./png/gallery-image-four.png";
export { default as GalleryImageFive } from "./png/gallery-image-five.png";

// new added images start
export { default as GalleryImageSix } from "./png/gallery-image-six.png";
export { default as GalleryImageSeven } from "./png/gallery-image-seven.png";
export { default as GalleryImageEight } from "./png/gallery-image-eight.png";
export { default as GalleryImageNine } from "./png/gallery-image-nine.png";
// export { default as GalleryImageTen } from "./png/gallery-image-three.png";
export { default as GalleryImageEleven } from "./png/gallery-image-eleven.png";
// export { default as GalleryImageTwelve } from "./png/gallery-image-tweleve.png";
export { default as GalleryImageThirteen } from "./png/gallery-image-thirteen.png";
export { default as GalleryImageFourteen } from "./png/gallery-image-fourteen.png";
export { default as GalleryImageFifteen } from "./png/gallery-image-fifteen.png";
// new images added wrap end

export { default as VideoImageOne } from "./png/video-image-one.png";
export { default as VideoImageTwo } from "./png/video-image-two.png";
export { default as VideoImageThree } from "./png/video-image-two.png";

// update wrap start
// export { default as VideoImageThree } from "./png/video-image-three.png";
// update wrap end

export { default as AllGalleryHeroImage } from "./png/gallery-hero-image.png";
// update wrap start
// export { default as AllImageOne } from "./png/all-image-one.png";
// export { default as AllImageTwo } from "./png/all-image-two.png";
// export { default as AllImageThree } from "./png/all-image-three.png";
// export { default as AllImageFour } from "./png/all-image-four.png";
// export { default as AllImageFive } from "./png/all-image-five.png";
// export { default as AllImageSix } from "./png/all-image-six.png";
// export { default as AllImageSeven } from "./png/all-image-seven.png";
// export { default as AllImageEight } from "./png/all-image-eight.png";
// export { default as AllImageNine } from "./png/all-image-nine.png";
// export { default as AllImageTen } from "./png/all-image-ten.png";
// export { default as AllImageEleven } from "./png/all-image-eleven.png";
// export { default as AllImageTwelve } from "./png/all-image-twelve.png";
// export { default as AllImageThirteen } from "./png/all-image-thirteen.png";
// export { default as AllImageFourteen } from "./png/all-image-fourteen.png";
// export { default as AllImageFifteen } from "./png/all-image-fifteen.png";
// update wrap end

export { default as AboutUsHeroImage } from "./png/about-us-hero-image.png";
export { default as FounderImage } from "./png/founder-image.png";
export { default as LeadershipImageOne } from "./png/leadership-image-one.png";
export { default as LeadershipImageTwo } from "./png/leadership-image-two.png";
export { default as LeadershipImageThree } from "./png/leadership-image-three.png";
export { default as LeadershipImageFour } from "./png/leadership-image-four.png";
export { default as LeadershipImageFive } from "./png/leadership-image-five.png";
export { default as LeadershipImageSix } from "./png/leadership-image-six.png";
export { default as LeadershipImageSeven } from "./png/leadership-image-seven.png";
export { default as CareerHeroImage } from "./png/career-hero-image.png";
export { default as MobileBgHeroImage } from "./png/mobile-hero-bg-image.png";
export { default as MobileContactHeroImage } from "./png/contact-mobile-image.png";
export { default as MobileBgMediaHeroImage } from "./png/mobile-media-hero-bg-image.png";
export { default as AllGalleryMobileHeroImage } from "./png/all-gallery-mobile-hero-bg-image.png";
export { default as AboutUsMobileHeroImage } from "./png/about-us-mobile-hero-img.png";
export { default as CeoMobileImage } from "./png/ceo-mobile-image.png";
export { default as CareerMobileHeroImage } from "./png/career-mobile-bg-image.png";

// export { default as ITHLogo } from "./png/ITHLogo.png";
// export { default as HeroImage } from "./png/hero-image.png";
// export { default as DellLogo } from "./png/dell-logo.png";
// export { default as ZohoLogo } from "./png/zoho-logo.png";
// export { default as SophosLogo } from "./png/sophos-logo.png";
// export { default as IBMLogo } from "./png/ibm-logo.png";
// export { default as CiscoLogo } from "./png/cisco-logo.png";
// export { default as MicrosoftLogo } from "./png/microsoft-logo.png";
// export { default as DellEMCLogo } from "./png/dell-emc-logo.png";
// export { default as HpLogo } from "./png/hp-logo.png";
// export { default as TermiiLogo } from "./png/termii-logo.png";
// export { default as LenovoLogo } from "./png/lenovo-logo.png";
// export { default as CommScopeLogo } from "./png/commscope.png";
// export { default as ExpressWalletLogo } from "./png/express-wallet-logo.png";
// export { default as Infrastructure } from "./png/infrastructure-image.png";
// export { default as SoftwareDevImage } from "./png/software-dev-image.png";
// export { default as Fintech } from "./png/fintech.png";
// export { default as WhoAreWeImg } from "./png/who-are-we-image.png";
// export { default as LightImage } from "./png/light-image.png";
// export { default as PartnersImage } from "./png/partners-image.png";
// export { default as SecurityTrainingImg } from "./png/security-training-img.png";
// export { default as BusinessEmailImg } from "./png/business-email-img.png";
// export { default as ContactHeroImg } from "./png/contact-hero-image.png";
// export { default as MediaHeroImg } from "./png/media-hero-image.png";
// export { default as HostImage } from "./png/host-images.png";
// export { default as InfrastructureImage } from "./png/infrastructure-img.png";
// export { default as TechnologyImg } from "./png/technology-img.png";
// export { default as GalleryImageOne } from "./png/gallery-image-one.png";
// export { default as GalleryImageTwo } from "./png/gallery-image-two.png";
// export { default as .png } from "./png/gallery-image-three.png";
// export { default as GalleryImageFour } from "./png/gallery-image-four.png";
// export { default as GalleryImageFive } from "./png/gallery-image-five.png";
// export { default as VideoImageOne } from "./png/video-image-one.png";
// export { default as VideoImageTwo } from "./png/video-image-two.png";
// export { default as VideoImageThree } from "./png/video-image-three.png";
// export { default as AllGalleryHeroImage } from "./png/all-gallery-hero-image.png";
// export { default as AllImageOne } from "./png/all-image-one.png";
// export { default as AllImageTwo } from "./png/all-image-two.png";
// export { default as AllImageThree } from "./png/all-image-three.png";
// export { default as AllImageFour } from "./png/all-image-four.png";
// export { default as AllImageFive } from "./png/all-image-five.png";
// export { default as AllImageSix } from "./png/all-image-six.png";
// export { default as AllImageSeven } from "./png/all-image-seven.png";
// export { default as AllImageEight } from "./png/all-image-eight.png";
// export { default as AllImageNine } from "./png/all-image-nine.png";
// export { default as AllImageTen } from "./png/all-image-ten.png";
// export { default as AllImageEleven } from "./png/all-image-eleven.png";
// export { default as AllImageTwelve } from "./png/all-image-twelve.png";
// export { default as AllImageThirteen } from "./png/all-image-thirteen.png";
// export { default as AllImageFourteen } from "./png/all-image-fourteen.png";
// export { default as AllImageFifteen } from "./png/all-image-fifteen.png";
// export { default as AboutUsHeroImage } from "./png/about-us-hero-image.png";
// export { default as FounderImage } from "./png/founder-image.png";
// export { default as LeadershipImageOne } from "./png/leadership-image-one.png";
// export { default as LeadershipImageTwo } from "./png/leadership-image-two.png";
// export { default as LeadershipImageThree } from "./png/leadership-image-three.png";
// export { default as LeadershipImageFour } from "./png/leadership-image-four.png";
// export { default as LeadershipImageFive } from "./png/leadership-image-five.png";
// export { default as LeadershipImageSix } from "./png/leadership-image-six.png";
// export { default as LeadershipImageSeven } from "./png/leadership-image-seven.png";
// export { default as CareerHeroImage } from "./png/career-hero-image.png";
// export { default as MobileBgHeroImage } from "./png/mobile-hero-bg-image.png";
// export { default as MobileContactHeroImage } from "./png/contact-mobile-image.png";
// export { default as MobileBgMediaHeroImage } from "./png/mobile-media-hero-bg-image.png";
// export { default as AllGalleryMobileHeroImage } from "./png/all-gallery-mobile-hero-bg-image.png";
// export { default as AboutUsMobileHeroImage } from "./png/about-us-mobile-hero-img.png";
// export { default as CeoMobileImage } from "./png/ceo-mobile-image.png";
// export { default as CareerMobileHeroImage } from "./png/career-mobile-bg-image.png";
