import {
  // GalleryImageOne,
  GalleryImageTwo,
  GalleryImageThree,
  GalleryImageFour,
  GalleryImageFive,
  GalleryImageSix,
  GalleryImageSeven,
  GalleryImageEight,
  GalleryImageNine,
  GalleryImageEleven,
  GalleryImageThirteen,
  GalleryImageFourteen,
  GalleryImageFifteen,
  GalleryImageSixteen,
} from "../../../../assets/images";

export const all_gallery = [
  GalleryImageSixteen,
  GalleryImageTwo,
  GalleryImageThree,
  GalleryImageFour,
  GalleryImageFive,
  GalleryImageSix,
  GalleryImageSeven,
  GalleryImageEight,
  GalleryImageNine,
  GalleryImageThree,
  GalleryImageEleven,
  GalleryImageFour,
  GalleryImageThirteen,
  GalleryImageFourteen,
  GalleryImageFifteen,
];
