import {
  AllImageEight,
  AllImageEleven,
  AllImageFifteen,
  AllImageFive,
  AllImageFour,
  AllImageFourteen,
  AllImageNine,
  AllImageOne,
  AllImageSeven,
  AllImageSix,
  AllImageTen,
  AllImageThirteen,
  AllImageThree,
  AllImageTwelve,
  AllImageTwo,
} from "../../../../assets/images";

export const all_gallery = [
  AllImageOne,
  AllImageTwo,
  AllImageThree,
  AllImageFour,
  AllImageFive,
  AllImageSix,
  AllImageSeven,
  AllImageEight,
  AllImageNine,
  AllImageTen,
  AllImageEleven,
  AllImageTwelve,
  AllImageThirteen,
  AllImageFourteen,
  AllImageFifteen,
];
