export const open_positions = [
  {
    job_title: "Product Designer",
    amount: "80-100k",
    duration: "monthly",
    content: "We’re looking for a mid-level product designer to join our team.",
    type: "Full Time",
    job_type: "Design",
    location: "Remote",
  },
  {
    job_title: "Product Designer",
    amount: "80-100k",
    duration: "monthly",
    content: "We’re looking for a mid-level product designer to join our team.",
    type: "Full Time",
    job_type: "Design",
    location: "Remote",
  },
  {
    job_title: "Product Designer",
    amount: "80-100k",
    duration: "monthly",
    content: "We’re looking for a mid-level product designer to join our team.",
    type: "Full Time",
    job_type: "Design",
    location: "Remote",
  },
  {
    job_title: "Product Designer",
    amount: "80-100k",
    duration: "monthly",
    content: "We’re looking for a mid-level product designer to join our team.",
    type: "Full Time",
    job_type: "Design",
    location: "Remote",
  },
  {
    job_title: "Product Designer",
    amount: "80-100k",
    duration: "monthly",
    content: "We’re looking for a mid-level product designer to join our team.",
    type: "Full Time",
    job_type: "Design",
    location: "Remote",
  },
  {
    job_title: "Product Designer",
    amount: "80-100k",
    duration: "monthly",
    content: "We’re looking for a mid-level product designer to join our team.",
    type: "Full Time",
    job_type: "Design",
    location: "Remote",
  },
];
