import {
  CiscoLogo,
  CommScopeLogo,
  DellEMCLogo,
  DellLogo,
  ExpressWalletLogo,
  HpLogo,
  IBMLogo,
  // LenovoLogo,
  MicrosoftLogo,
  SophosLogo,
  TermiiLogo,
  ZohoLogo,
} from "../../../assets/images";

export const trusted_partners = [
  DellLogo,
  ZohoLogo,
  SophosLogo,
  IBMLogo,
  CiscoLogo,
  MicrosoftLogo,
  DellEMCLogo,
  HpLogo,
  TermiiLogo,
  IBMLogo,
  CiscoLogo,
  MicrosoftLogo,
  IBMLogo,
  CiscoLogo,
  MicrosoftLogo,
  DellEMCLogo,
  HpLogo,
  TermiiLogo,
  // LenovoLogo,
  CommScopeLogo,
  ExpressWalletLogo,
  CiscoLogo,
  MicrosoftLogo,
  DellEMCLogo,
  HpLogo,
  TermiiLogo,
  // LenovoLogo,
  CommScopeLogo,
  DellEMCLogo,
  HpLogo,
  TermiiLogo,
  HpLogo,
  TermiiLogo,
  ExpressWalletLogo,
];
